# taken almost literally from https://github.com/purcell/package-lint/blob/0e27abf2e65340dc1523b27b923650b863472a5a/.github/workflows/test.yml

name: CI

on:
  push:
    paths-ignore:
    - '**.md'
  schedule:
    - cron: '0 0 1 */2 *'

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        emacs_version:
          - 25.3
          - 26.3
          - 27.2
          - 28.2
          - 29.1
          - 29.2
          - 29.3
          - snapshot
        include:
          - emacs_version: snapshot
            allow_failure: true

    steps:
      # enh-ruby mode needs ruby; in principle we don't care much about the
      # version.
    - uses: ruby/setup-ruby@v1
      with:
        ruby-version: 3.3

    - uses: purcell/setup-emacs@master
      with:
        version: ${{ matrix.emacs_version }}

    - uses: porras/setup-cask@master

    - uses: actions/checkout@v1

    - name: Install dependencies
      run: make deps

    - name: Run tests
      run: make test

    - name: Lint package and code
      run: make check
